expenses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ExpenseView.as_view(), name='expenses'),
    path('create/', views.ExpenseCreateView.as_view(), name='expenses-create'),
    path('<int:pk>/update/', views.ExpenseUpdateView.as_view(), name='expenses-update'),
    path('<int:pk>/delete/', views.ExpenseDeleteView.as_view(), name='expenses-delete'),
]

school_account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('u/', include('django.contrib.auth.urls')),
    path('', include('student_ledger.urls')),
    path('xp/', include('expenses.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student_ledger/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BillListView.as_view(), name='home'),
    path('settings/', views.settings_view, name='settings'),

    path('session/<int:pk>/update/', views.SessionUpdateForm.as_view(), name='session-update'),
    path('term/<int:pk>/update/', views.TermUpdateForm.as_view(), name='term-update'),
    path('class/<int:pk>/update/', views.ClassUpdateForm.as_view(), name='class-update'),
    path('bank/<int:pk>/update/', views.BankUpdateForm.as_view(), name='bank-update'),

    path('students/', views.StudentListView.as_view(), name='students'),
    path('students/create/', views.StudentCreateView.as_view(), name='student-create'),
    path('students/<int:pk>/detail/', views.StudentDetailView.as_view(), name='student-detail'),
    path('students/<int:pk>/update/', views.StudentUpdateView.as_view(), name='student-update'),
    path('students/<int:pk>/delete/', views.StudentDeleteView.as_view(), name='student-delete'),

    path('bill/<int:pk>/detail/', views.BillDetailView.as_view(), name='bill-detail'),
    path('bill/create/', views.BillCreateView.as_view(), name='bill-create'),
    path('bill/generate/', views.BillGenerateView.as_view(), name='bill-generate'),
     path('bill/<int:pk>/update/', views.BillUpdateView.as_view(), name='bill-update'),
    path('bill/<int:pk>/delete/', views.BillDeleteView.as_view(), name='bill-delete'),

    path('payment/<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment-delete'),


    path('bill/<int:pk>/pay/', views.BillPay.as_view(), name='bill-payment'),
]

student_ledger/models.py
from django.db import models
from django.db.models import Sum
from django.utils.timezone import now
from django.urls import reverse

class StudentClass(models.Model):
    CATEGORIES = [
        ('primary', 'Primary'),
        ('junior', 'Junior'),
        ('secondary', 'Secondary'),
    ]
    name = models.CharField(max_length=100, unique=True)
    category = models.CharField(max_length=20, choices=CATEGORIES)

    def __str__(self):
        return self.name


class AcademicSession(models.Model):
    name = models.CharField(max_length=200, unique=True)
    current = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class AcademicTerm(models.Model):
    name = models.CharField(max_length=200, unique=True)
    current = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Bank(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name} ({self.code})'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'code'], name='unique_bank'),
        ]


class Student(models.Model):
    student_id = models.CharField(max_length=10, unique=True)
    surname = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    other_names = models.CharField(max_length=200, blank=True)
    contact_number = models.CharField(max_length=200, blank=True)
    current_class = models.ForeignKey(StudentClass, on_delete=models.SET_NULL, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.surname} {self.firstname} {self.other_names}'


class Bill(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    session = models.ForeignKey(AcademicSession, on_delete=models.CASCADE)
    term = models.ForeignKey(AcademicTerm, on_delete=models.CASCADE)
    class_for = models.ForeignKey(StudentClass, on_delete=models.SET_NULL, null=True)
    amount_payable = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return f"{self.student}'s bill"

    def get_absolute_url(self):
        return reverse('bill-detail', kwargs={'pk': self.pk})

    @property
    def paid(self):
        tt = Payment.objects.filter(bill=self).aggregate(Sum('amount_paid'))
        val = tt['amount_paid__sum'] if tt['amount_paid__sum'] else 0
        return val

    @property
    def balance(self):
        total = self.amount_payable - self.paid
        return 0 if total < 0 else total

    @property
    def credit(self):
        total = self.amount_payable - self.paid
        if total > 0:
            return  0
        else: return abs(total)


class Payment(models.Model):
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE)
    amount_paid = models.DecimalField(max_digits=11, decimal_places=2)
    date = models.DateField(default=now)
    comment = models.TextField(blank=True)

    def __str__(self):
        return f'Payment for {self.bill}'

student_ledger/views.py
from django.db.models.functions import Coalesce
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.db.models.aggregates import Sum
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView, BSModalFormView

from .models import Student, StudentClass, Bank, Bill, Payment, AcademicSession, AcademicTerm

from .forms import StudentForm, TermForm, SessionForm, ClassForm, BankForm, BillForm, BillGenerateForm, BillPayForm, StatementSearchForm, SearchForm


@login_required
def settings_view(request):
    if request.method == 'POST':
        termform = TermForm(request.POST, prefix='term')
        if termform.is_valid():
            termform.save()

        sessionform = SessionForm(request.POST, prefix='session')
        if sessionform.is_valid():
            sessionform.save()

        classform = ClassForm(request.POST, prefix='classes')
        if classform.is_valid():
            classform.save()

        bankform = BankForm(request.POST, prefix='banks')
        if bankform.is_valid():
            bankform.save()



    terms = AcademicTerm.objects.all()
    sessions = AcademicSession.objects.all()
    classes = StudentClass.objects.all()
    banks = Bank.objects.all()

    termform = TermForm(prefix='term')
    sessionform = SessionForm(prefix='session')
    classform = ClassForm(prefix='classes')
    bankform = BankForm(prefix="banks")

    context = {
        "terms": terms,
        "sessions":sessions,
        "classes": classes,
        "banks": banks,
        "term_form": termform,
        "session_form": sessionform,
        "class_form": classform,
        "bank_form": bankform,
    }

    return render(request, 'student_ledger/settings.html', context)


class SessionUpdateForm(LoginRequiredMixin, BSModalUpdateView):
    model = AcademicSession
    form_class = SessionForm
    template_name = 'student_ledger/update_form.html'
    success_url = reverse_lazy('settings')
    context_object_name = 'object'


class TermUpdateForm(LoginRequiredMixin, BSModalUpdateView):
    model = AcademicTerm
    form_class = TermForm
    template_name = 'student_ledger/update_form.html'
    success_url = reverse_lazy('settings')
    context_object_name = 'object'


class ClassUpdateForm(LoginRequiredMixin, BSModalUpdateView):
    model = StudentClass
    form_class = ClassForm
    template_name = 'student_ledger/update_form.html'
    success_url = reverse_lazy('settings')
    context_object_name = 'object'


class BankUpdateForm(LoginRequiredMixin, BSModalUpdateView):
    model = Bank
    form_class = BankForm
    template_name = 'student_ledger/update_form.html'
    success_url = reverse_lazy('settings')
    context_object_name = 'object'


class StudentListView(LoginRequiredMixin, ListView):
    model = Student


class StudentCreateView(LoginRequiredMixin, BSModalCreateView):
    form_class = StudentForm
    success_url = reverse_lazy('students')
    success_message = 'Student was successfully created.'
    template_name = 'student_ledger/create_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Register new student'
        context['button'] = 'Save new student'
        return context


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    template_name = 'student_ledger/student_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Register new student'
        context['button'] = 'Save new student'
        return context


class StudentUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('students')
    success_message = 'Student was successfully updated.'
    template_name = 'student_ledger/update_form.html'
    context_object_name = 'object'


class StudentDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Student
    template_name = 'student_ledger/delete_form.html'
    success_message = 'Success: Student was deleted.'
    success_url = reverse_lazy('students')
    context_object_name = "object"


"""

   **********************  BILLS  ****************

"""

class BillListView(LoginRequiredMixin, View):
    """ Show statement for student bills """
    template_name = 'student_ledger/statement.html'
    form_class = StatementSearchForm

    def get(self, request, *args, **kwargs):
        params = {x:y for x, y in request.GET.items() if y}
        aggregation = {
            "total_bill": Coalesce(Sum('amount_payable'),0),
            "total_paid": Coalesce(Sum('payment__amount_paid'), 0),
            "total_debt": Coalesce(Sum('amount_payable'), 0) - Coalesce(Sum('payment__amount_paid'), 0)
        }

        bills = Bill.objects.all()
        bills_aggregate = bills.aggregate(**aggregation)

        if params:
            bills = Bill.objects.filter(**params)
            bills_aggregate = bills.aggregate(**aggregation)

        context = {
            "search": self.form_class(initial=params),
            "bills": bills,
            "bills_aggregate":bills_aggregate,
        }
        return render(request, self.template_name, context)


class BillCreateView(LoginRequiredMixin, BSModalCreateView):
    form_class = BillForm
    success_url = reverse_lazy('home')
    template_name = 'student_ledger/create_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add a new bill'
        context['button'] = 'Create invoice'
        return context


class BillGenerateView(LoginRequiredMixin, BSModalFormView):
    form_class = BillGenerateForm
    template_name = 'student_ledger/generate-bill.html'
    success_url = reverse_lazy('home')
    success_message = "Bills successfully created"


    def form_valid(self, form):
        if not self.request.is_ajax():
            class_for = form.cleaned_data['class_for']
            session = form.cleaned_data['session']
            term = form.cleaned_data['term']
            amount_payable = form.cleaned_data['amount_payable']
            students = Student.objects.filter(current_class=class_for, active=True)
            bills = []
            for student in students:
                bills.append(Bill(
                    student=student,
                    session=session,
                    term=term,
                    class_for=class_for,
                    amount_payable=amount_payable
                ))
            Bill.objects.bulk_create(bills)

        return super().form_valid(form)


class BillPay(BSModalCreateView):
    form_class = BillPayForm
    template_name = 'student_ledger/create_form.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Payment'
        context['button'] = 'Add payment'
        return context

    def form_valid(self, form):
        bill = get_object_or_404(Bill, pk=self.kwargs['pk'])
        form.instance.bill = bill
        return super().form_valid(form)


class BillDetailView(LoginRequiredMixin, DetailView):
    model = Bill
    template_name = "student_ledger/bill-detail.html"



class BillUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Bill
    form_class = BillForm
    success_url = reverse_lazy('home')
    success_message = 'Bill was successfully updated.'
    template_name = 'student_ledger/update_form.html'
    context_object_name = 'object'


class BillDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Bill
    template_name = 'student_ledger/delete_form.html'
    success_message = 'Success: Bill was deleted.'
    success_url = reverse_lazy('home')
    context_object_name = "object"


class PaymentDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Payment
    template_name = 'student_ledger/delete_form.html'
    success_message = 'Success: Payment was deleted.'
    context_object_name = "object"

    def get_success_url(self):
        return self.object.bill.get_absolute_url()

student_ledger/templates/student_ledger/bill-detail.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}
    {{object}}
{% endblock title %}


{% block content %}

<div class="btn-toolbar mb-2">
    <button type="button" name="button" class="btn btn-sm btn-outline-secondary">
      {{object.session}} Session
    </button>
    <button type="button" name="button" class="btn btn-sm btn-outline-secondary">
      {{object.term}}
    </button>
    <button type="button" name="button" class="btn btn-sm btn-outline-secondary">
      {{object.class_for}}
    </button>
</div>

<div class="row">
    <div class="col-6 col-md-4">
        <div class="card bg-primary text-white">
            <div class="card-body">
              <h5 class="card-title">Total Amount Payable</h5>
              <h6 class="card-subtitle mb-2"> {{currency}} {{object.amount_payable|intcomma}} </h6>
            </div>
        </div>
    </div>

    <div class="col-6 col-md-4">
        <div class="card bg-success text-white">
            <div class="card-body">
              <h5 class="card-title">Total Amount Paid</h5>
              <h6 class="card-subtitle mb-2">{{currency}} {{object.paid|intcomma}}</h6>
            </div>
        </div>
    </div>

    <div class="col-6 col-md-4">
        <div class="card bg-danger text-white">
            <div class="card-body">
              <h5 class="card-title">Debt</h5>
              <h6 class="card-subtitle mb-2">{{currency}} {{object.balance|intcomma}}</h6>
            </div>
        </div>
    </div>



</div>

<div class="table-responsive">
    <table class="mt-2 mb-2 table table-bordered">
        <thead>
            <tr>
                <th class="text-danger">Payments</th>
            </tr>
        </thead>
        <tbody>
            <tr>

                <td>
                    {% if object.payment_set.all %}
                        <ul class="list-group">
                            {% for item in object.payment_set.all %}
                            <li class="list-group-item">
                                <div class="float-right">
                                    <small class="form-text text-muted">
                                        {{item.date}}
                                    </small>
                                    <a data-form-url="{% url 'payment-delete' item.id %}" data-toggle="tooltip" title="Delete" class="bs-modal text-danger"><span data-feather="trash"></span></a>
                                </div>
                                {{item.bank}}
                                <span data-feather="arrow-right"></span>
                                <strong>{{currency}} {{item.amount_paid|intcomma}}</strong>

                                <small class="form-text text-muted">
                                    {{item.comment}}
                                </small>
                            </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>There are no payment yet</p>
                    {% endif %}



                </td>
            </tr>


        </tbody>
    </table>
</div>


<div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>



{% endblock content %}


{% block scripts %}
    <script>
        $(document).ready(function() {
            $(".bs-modal").each(function () {
                $(this).modalForm({
                    formURL: $(this).data('form-url')
                });
            });
        });
    </script>



{% endblock scripts %}

student_ledger/templates/student_ledger/create_form.html
<form method="POST">
    {% csrf_token %}
    <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{title}} </h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>

    <div class="modal-body">
        <div class="form-row invalid">
            {% for field in form %}
                <div class="form-group col-sm-6">
                    {{field.label_tag}}
                    {{field}}

                    <small class="form-text text-muted">
                    {% for error in field.errors %}
                        <span class="text-danger">{{error}}</span>
                    {% endfor %}
                    </small>
                </div>
            {% endfor %}
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary">{{button}} </button>
      </div>
</form>

student_ledger/templates/student_ledger/generate-bill.html
<form method="POST">
    {% csrf_token %}
    <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Generate Bill</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>

    <div class="modal-body">
        <div class="form-row invalid">
            {% for field in form %}
                <div class="form-group col-sm-4">
                    {{field.label_tag}}
                    {{field}}

                    <small class="form-text text-muted">
                    {% for error in field.errors %}
                        <span class="text-danger">{{error}}</span>
                    {% endfor %}
                    </small>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary">Generate </button>
      </div>
</form>

student_ledger/templates/student_ledger/settings.html
{% extends 'base.html' %}


{% block title %}
    Settings
{% endblock title %}


{% block content %}

<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Academic Terms</a>
      <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Academic Sessions</a>
      <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Classes</a>
      <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Banks</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">

        <form method="POST" class="form-inline">
          {% csrf_token %}
          <div class="form-group m-2">
            Add new term
          </div>
          {% for field in term_form %}
            <div class="form-group m-2">
              {{field}}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary btn-sm m-2">Add new term</button>
        </form>

        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>Term Name</th>
              <th>Current</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for term in terms %}
            <tr>
              <td>{{term.name}}</td>
              <td>{{term.current}}</td>
              <td>
                <a data-form-url="{% url 'term-update' term.id %}" class="bs-modal"><span data-feather="edit"></span></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="tab-pane" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
        <form method="POST" class="form-inline">
          {% csrf_token %}
          <div class="form-group m-2">
            Add new session
          </div>
          {% for field in session_form %}
            <div class="form-group m-2">
              {{field}}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary btn-sm m-2">Add new session</button>
        </form>
        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>Session Name</th>
              <th>Current</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for session in sessions %}
            <tr>
              <td>{{session.name}}</td>
              <td>{{session.current}}</td>
              <td>
                <a data-form-url="{% url 'session-update' session.id %}" class="bs-modal"><span data-feather="edit"></span></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="tab-pane" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
        <form method="POST" class="form-inline">
          {% csrf_token %}
          <div class="form-group m-2">
            Add new class
          </div>
          {% for field in class_form %}
            <div class="form-group m-2">
              {{field}}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary btn-sm m-2">Add new class</button>
        </form>

        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>Class Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for class in classes %}
            <tr>
              <td>{{class.name}}</td>
              <td>
                <a data-form-url="{% url 'class-update' class.id %}" class="bs-modal"><span data-feather="edit"></span></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>


      </div>

      <div class="tab-pane" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
        <form method="POST" class="form-inline">
          {% csrf_token %}
          <div class="form-group m-2">
            Add new bank
          </div>
          {% for field in bank_form %}
            <div class="form-group m-2">
              {{field}}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary btn-sm m-2">Add bank</button>
        </form>

        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>Bank Name</th>
              <th>Code</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for bank in banks %}
            <tr>
              <td>{{bank.name}}</td>
              <td>{{bank.code}}</td>
              <td>
                <a data-form-url="{% url 'bank-update' bank.id %}" class="bs-modal"><span data-feather="edit"></span></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>


    </div>
  </div>
</div>

<div class="modal fade" role="dialog" id="modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock content %}



{% block scripts %}
    <script>
        $(document).ready(function() {

            $(".bs-modal").each(function () {
                $(this).modalForm({
                    formURL: $(this).data('form-url')
                });
            });
        });
    </script>
{% endblock scripts %}

student_ledger/templates/student_ledger/student_detail.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}
    {{object}}
{% endblock title %}


{% block toolbar %}
<div class="btn-toolbar mb-2 mb-md-0">
    <a data-form-url="{% url 'student-update' object.id %}" name="button" class="btn btn-sm btn-outline-secondary bs-modal">
      <span data-feather="edit"></span>
      Update
    </a>
  </div>
{% endblock toolbar %}

{% block content %}

<div class="btn-toolbar mb-2">
    <button type="button" name="button" class="btn btn-sm btn-outline-secondary">
      Current Class: {{object.current_class}}
    </button>
</div>


<div class="table-responsive">
    <h5>Bill History</h5>
    <table class="mt-2 mb-2 table table-hover">
        <thead>
            <tr>
                <th class="text-danger">Bills</th>
                <th class="text-danger">Total</th>
                <th class="text-danger">Payments</th>
            </tr>
        </thead>
        <tbody>
            {% for bill in object.bill_set.all %}
                <tr>
                    <td><a href="{% url 'bill-detail' bill.id %}">{{bill}}</a></td>
                    <td>{{bill.amount_payable|intcomma}}</td>
                    <td>{{bill.paid|intcomma}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>



{% endblock content %}


{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $(".bs-modal").each(function () {
                $(this).modalForm({
                    formURL: $(this).data('form-url')
                });
            });

        });
    </script>
{% endblock scripts %}

student_ledger/templates/student_ledger/student_list.html
{% extends 'base.html' %}


{% block title %}
    Students
{% endblock title %}

{% block toolbar %}
<div class="btn-toolbar mb-2 mb-md-0">
    <button type="button" name="button" class="btn btn-sm btn-outline-secondary" id="payer-create">
      <span data-feather="plus"></span>
      Register a new student
    </button>
  </div>
{% endblock toolbar %}


{% block content %}


{% if object_list %}
    <table class="table table-hover datatabletable">
        <thead class="thead-light">
            <tr>
                <th>Fullname</th>
                <th>Current Class</th>
                <th>Contact</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>

            {% for item in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'student-detail' item.id %}">{{item}}</a>
                    </td>
                    <td>{{item.current_class}}</td>
                    <td>{{item.contact_number}}</td>
                    <td>
                        <a data-form-url="{% url 'student-update' item.id %}" class="bs-modal"><span data-feather="edit"></span></a>
                        <a data-form-url="{% url 'student-delete' item.id %}" class="bs-modal text-danger"><span data-feather="delete"></span></a>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    There are currently no registered student
{% endif %}


<div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>


{% endblock content %}



{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#payer-create").modalForm({
                formURL: "{% url 'student-create' %}"
            });

            $(".bs-modal").each(function () {
                $(this).modalForm({
                    formURL: $(this).data('form-url')
                });
            });

        });
    </script>
{% endblock scripts %}

student_ledger/templates/student_ledger/update_form.html
<form method="POST">
    {% csrf_token %}
    <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Update {{object}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>

    <div class="modal-body">
        <div class="form-row invalid">
            {% for field in form %}
                <div class="form-group col-sm-6">
                    {{field.label_tag}}
                    {{field}}

                    <small class="form-text text-muted">
                    {% for error in field.errors %}
                        {{error}}
                    {% endfor %}
                    </small>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary">Update</button>
      </div>
</form>